name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  board-ci:
    name: Arduino Uno
    strategy:
      fail-fast: true
      matrix:
        board:
          - arduino-uno
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-01-07
          override: true
          components: rust-src
      - name: Install avr-gcc, binutils, and libc
        run: sudo apt-get install -y avr-libc binutils-avr gcc-avr
      - name: Build
        run: cargo build --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: $(echo pwd)/target/avr-atmega328p/release/nswi170-final-project.elf
